from . import test_bitacora
from . import test_cobro_arqueo
from . import test_cobro_bitacora
from . import test_cobro_confirmar
from . import test_cobro_lectura
from . import test_cobro_pago
from . import test_entrega_confirmar
from . import test_hoja_carga
from . import test_inicio
from . import test_entrega_lectura
from . import test_entrega_vista_previa
from . import test_enviar
from . import test_lo_de_siempre
from . import test_pagina_y_rutas
from . import test_pendiente_cobro
from . import test_zona_y_seguridad
